version: '2.2'
services:
  file-storage:
    ports:
      - "8090:8090"
    build:
      context: .
    container_name: file-storage
    volumes:
      - "./maven-rep:/root/.m2"
      - "D:/odeyalo/dev/microservices/filestorage/videos:/odeyalo/dev/microservices/filestorage/videos"
      - "D:/odeyalo/dev/microservices/filestorage/videos:/odeyalo/dev/microservices/filestorage/videos/temp"
      - "D:/odeyalo/dev/microservices/filestorage/images:/odeyalo/dev/microservices/filestorage/images"
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    env_file:
      - local.env
    networks:
      - netflix


networks:
  netflix:
    external: true
