name: file-storage
on: [ push, pull_request ]

env:
  ACCESS_TOKEN: ${{ secrets.pritn }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker compose
        run: docker-compose -f ${GITHUB_WORKSPACE}/docker-compose.test.yml up --abort-on-container-exit
