name: file-storage
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker containers
      - run: entrypoint.sh
      - name: Build docker compose
        run: docker-compose up -d
