name: file-storage
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker containers
        run: docker build -t /github/file-storage-test-image .
      - name: current directory
        run: pwd
      - name: files
        run: ls
      - name: Build docker compose
        run: docker-compose -f ${GITHUB_WORKSPACE}/.github/docker-compose.test.yml up --abort-on-container-exit
