name: file-storage
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker containers
        run: chmod +x ${GITHUB_WORKSPACE}/.github/entrypoint.sh ${GITHUB_WORKSPACE}/.github/entrypoint.sh

      - name: Build docker compose
        run: docker-compose up -d
